### PR TITLE
Make sure default max_connections passed to Cowboy is "infinity"

### LINKED ISSUE #55: Make sure default max_connections passed to Cowboy is not limited to 1024
See [this comment for background](https://github.com/rabbitmq/rabbitmq-web-mqtt/issues/28#issuecomment-499754232).

### PR DESCRIPTION
**Pull request by michaelklishin**
Like we already do for all but the WebSockets-based protocols. See #28 for background.

Closes #55.

### CODE REVIEW

**Review by essen — COMMENTED** [review]
Have not taken a close look but if everything else defaults to infinity then I suppose doing it here wouldn't hurt. We'll consider increasing the default in Ranch 2.0 as well.

**Comment by michaelklishin** [comment]
@essen thanks. Actually my first attempt did not work on an actual running node. Please take another look :) I personally think that Ranch should default to `infinity` as such defaults are hard to get right in practice. Let the user who has the metrics do it when she figures it's necessary ;)

**Review by lukebakken — APPROVED** [review]
:+1: schema test passes, `ranch:info()` shows `infinity` when broker is started with this plugin.

**Comment by lukebakken** [comment]
Backported to `v3.7.x`

**Pull request merged**
